### ISSUE TITLE
Decrypter Adaption

### ISSUE THREAD

**Issue by makiele** [chester4444/decrypter#1]
Hallo chester4444,

erstmal vielen vielen Dank für deine Arbeit. Aufgrund der dünnen Datenlage zum Thema Smart Meter hat gerade dein PDF zu dem Thema unheimlich weitergeholfen.
Da ich bei Thema Cryptografie und der Programmierung aber nicht so viel Know-How habe, wollte ich fragen, ob du mir weiterhelfen kannst.

Auch ich hab den Smart Meter Landis+Gyr E450 im Einsatz, jedoch ist dieser von den Wiener Netzen.
Ich konnte bereits Daten erfolgreich über die optische Schnittstelle empfangen und diese dank deines Dokuments zerlegen. Woran ich jetzt noch scheitere ist die Entschlüsselung des Ciphertext.

Es gibt ein paar kleine Unterschiede zu den Daten von Energie Burgenland, vielleicht kannst du mir eine Tipp geben, was bei deinem decrypter geändert gehört, um auch die Daten meines Zählers erfolgreich zu entschlüsseln.

Der Zähler spuckt jede Sekunde Daten im Umfang von 105 Bytes über die optische Schnittstelle aus
**0x7E** - HDLC Delimiter 
**A067CEFF0313XXXX** - HDLC Header 8 Bytes (letzten vier Stellen unterscheiden sich zu deinem)
**E6E700** - LLC Header 6 Bytes
**DB08** - next two bytes 
**4C475A67XXXXXXXX** - System-Title 8 bytes
**4F** - Length of remainig bytes
**20** - security byte
**0001005E** - nonce
**Ciphertext** - 62 bytes
**Authentication Tag** - 12 bytes
**CRC Code** - 2 bytes
**0x7E** - HDLC Delimiter 

**Encryption Key** = 16 Bytes
Die Wiener Netze stellen aber im Gegensatz zu Energie Burgenland keinen Authentication Key zur Verfügung. Somit kann ich keine ADD generieren.

Momentan zapfe ich die Daten noch per Hand mit einem PC und würde sie dann per MQTT an deine Decrypter-Software senden - um einfach mal zu sehen, wie die entschlüsselten Daten aussehen und ob sie sich überhaupt erfolgreich entschlüsseln lassen.

für Hilfe wäre ich sehr dankbar.

mfg

**Comment by chester4444** [comment]
Hallo makiele,

schick mir mal einen gesamten Frame von dir, dann kann ich gerne den decrypter anpassen.

**Comment by makiele** [comment]
Hi,
hier ein ganzer Frame

`7EA067CEFF031338BDE6E700DB084C475A6773436EB94F200001005E2B10F9C9F2E62AE3D34663111872A737EF5A76A05457231AE52C591B0DBF7D24D2C3B622F4DDB418EA8027C021E1A30E0AC60B803CAC89C613015EE3E4E3124D894D06F7224AEE2F8B838C057E`

vielen dank schon mal

**Comment by pocki80** [comment]
Hallo. Stimmt das mit dem Authentication-Tag überhaupt im Zusammenhang mit security-byte=0x20?
Dem Greenbook zufolge sagt das security-byte folgendes:
bit 4=1 -> authentication
bit 5=1 -> encryption
also ist 0x20 binär 0010.0000: bit4=0 und bit5=1 (von rechts beginnend mit 0 gezählt)
0x20 bedeutet somit "encryption only"
0x30 bedeutet somit "encryption and authentication".

Im Falle von 0x30 enthält die payload also 12 byte "autentication tag"
Im Falle von 0x20 eben nicht. Was genau ist dann die korrekte Dechiffrier-Methode? Müsste es mit aes-128-ctr gehen, also ohne auth-tag und mit einer ergänzuung des IV um 0x00 00 00 00?

BTW: ich habe einen SmartMeter vom Typ "Iskraemeco AM550" und von den Wiener Netzen nur einen Aes-Schlüssel (16byte) bekommen. Einen Auth-Key gibt es keinen. Der Smartmeter sendet security-byte 0x20, also encryption-only. Ich habe es noch nicht geschafft, mit meinem Aes-Key den Payload zu decodieren. 

Bei mir sieht ein Paket so aus:
```
7e a067 cf022313 fbf1 e6e700 
db08 49534b69746c83b4 4f 20 0003b1d9 
16c20deacbd13348b07a7b3a850ac5c1ce55a70e 
a57a15c284c6ba47326e2a598f3276b7a4a15c03 
93c4492ca83a560b3b535d158a22055f89a1117c 
aa91 895fcf63c505b4207b16a9a3 f679 7e
```

**Comment by pocki80** [comment]
> Auch ich hab den Smart Meter Landis+Gyr E450 im Einsatz, jedoch ist dieser von den Wiener Netzen.
> Ich konnte bereits Daten erfolgreich über die optische Schnittstelle empfangen und diese dank deines Dokuments zerlegen. Woran ich jetzt noch scheitere ist die Entschlüsselung des Ciphertext.

Makiele, es wird im Forum von gurux.fi vermutet, dass WienerNetze falsche AES-Keys im Webportal anzeigt. Je mehr Kunden **nicht-funktionierende Schlüsselcodes für die Kundenschnittstelle bemängeln**, umso eher werden die WienerNetze das richten. Ich lade dich ein, die WienerNetze diesbezüglich zu kontaktieren! Ich gehe denen auch schon seit dem Frühjahr 2020 auf die Nerven...

**Comment by makiele** [comment]
hi @pocki80,

vielen dank für deinen input. nachdem du die geschichte mit dem security byte erwähnt hast, habe ich mir das green book auch nochmal druchgelesen und es mit CTR probiert - selbes ergebnis, der entschlüsselte ciphertext ergibt keinen sinn.

entweder machen wir also etwas bei der entschlüsselung falsch (auch deshalb habe ich auf eine angepasste version von @chester4444 gehofft) oder, die wiener netze geben einen falschen schlüssel aus. der mancherorts erwähnte firmware-bug ergibt meiner meinung nach keinen sinn, da ja in unser beider fälle unterschiedlich meter-hersteller betroffen wären

ich hatte auch bereits die zweifelhafte ehre, mit den wiener netzen in konakt zu treten und kann den fehlenden wille zur hilfe bei diesem problem bestätigen...

**Comment by chester4444** [comment]
Ich hab den decrypter damals schnell mal runterprogrammiert (und aktuell hab ich den nicht mehr im Einsatz, weill
ich auf den ESP8266 gewechselt hab)

ich hab grad schnell was eingecheckt - testen kann ich das leider nicht, also probiers mal aus und berichte

Aja folgendes noch
`#define CT_LEN 77`
auf
`#define CT_LEN 74`
ändern.

**Comment by chester4444** [comment]
versuch mal folgendes (alles in einer Zeile)
`mosquitto_pub -t /sm/encrypted -m "4C475A6773436EB94F200001005E2B10F9C9F2E62AE3D34663111872A737EF5A76A05457231AE52C591B0DBF7D24D2C3B622F4DDB418EA8027C021E1A30E0AC60B803CAC89C613015EE3E4E3124D894D06F7224AEE2F8B83"`

das ist dein Frame von oben - etwas zurechtgestutzt
(DEBUG einschalten, und dann berichte)

**Comment by makiele** [comment]
ich hab jetzt mal einge an den decrypter übertragen - aber der plaintext wirkt für mich nicht so, als wäre er richtig.
ich kann weder uhrzeit noch eine seriennumer aus dem hex code herauslesen.

nur zur kurzen verständnisfrage ich habe in zeile 38 meinen key folgendermaßen eingetragen (key hier maskiert)
```
static const uint8_t gcm_key[] = {
  0xAA,0xBB,0xCC,0xDD,0xEE,0xFF,0x11,0x22,0x33,0x44,0x55,0x66,0x77,0x88,0x99,0x00 // comma separated list of 16 bytes
};
```
ist das so erlaubt, oder mach ich hier schon das ergebnis hin?

**Comment by chester4444** [comment]
> ist das so erlaubt, oder mach ich hier schon das ergebnis hin?

das passt so

**Comment by chester4444** [comment]
> ich hab jetzt mal einge frames an den decrypter übertragen

zeig her, wie du das machst, Debugausgaben wären hilfreich

**Comment by makiele** [comment]
```
Message received in topic: /sm/encrypted

4C 47 5A 67 73 43 6E B9 4F 20 00 01 00 5E 2B 10
F9 C9 F2 E6 2A E3 D3 46 63 11 18 72 A7 37 EF 5A
76 A0 54 57 23 1A E5 2C 59 1B 0D BF 7D 24 D2 C3
B6 22 F4 DD B4 18 EA 80 27 C0 21 E1 A3 0E 0A C6
0B 80 3C AC 89 C6 13 01 5E E3 E4 E3 12 4D 89 4D
06 F7 22 4A EE 2F 8B 83
gcm_iv:
0000 - 4c 47 5a 67 73 43 6e b9-00 01 00 5e               LGZgsCn....^
gcm_ct:
0000 - 2b 10 f9 c9 f2 e6 2a e3-d3 46 63 11 18 72 a7 37   +.....*..Fc..r.7
0010 - ef 5a 76 a0 54 57 23 1a-e5 2c 59 1b 0d bf 7d 24   .Zv.TW#..,Y...}$
0020 - d2 c3 b6 22 f4 dd b4 18-ea 80 27 c0 21 e1 a3 0e   ..."......'.!...
0030 - 0a c6 0b 80 3c ac 89 c6-13 01 5e e3 e4 e3 12 4d   ....<.....^....M
0040 - 89 4d 06 f7 22 4a ee 2f-8b 83                     .M.."J./..


Ciphertext:
0000 - 2b 10 f9 c9 f2 e6 2a e3-d3 46 63 11 18 72 a7 37   +.....*..Fc..r.7
0010 - ef 5a 76 a0 54 57 23 1a-e5 2c 59 1b 0d bf 7d 24   .Zv.TW#..,Y...}$
0020 - d2 c3 b6 22 f4 dd b4 18-ea 80 27 c0 21 e1 a3 0e   ..."......'.!...
0030 - 0a c6 0b 80 3c ac 89 c6-13 01 5e e3 e4 e3 12 4d   ....<.....^....M
0040 - 89 4d 06 f7 22 4a ee 2f-8b 83                     .M.."J./..
Plaintext:
0000 - 6d 97 b0 5a ec 1a 9f 17-bc 31 31 61 f9 e4 16 8a   m..Z.....11a....
0010 - 48 cc 2b 43 0f 70 0b 4f-0d d1 c5 1c 0b 63 14 76   H.+C.p.O.....c.v
0020 - d8 0c b6 15 92 8b 66 cb-b8 77 f0 86 37 c4 5b 3f   ......f..w..7.[?
0030 - 52 55 ae a2 63 75 7b 21-2c cb 45 71 c0 9f 6b f8   RU..cu{!,.Eq..k.
0040 - 5a 56 dc 7f 19 38 59 d8-0f a2                     ZV...8Y...
```

**Comment by chester4444** [comment]
IV passt, CT passt auch
nur der Plaintext passt definitiv nicht

**Comment by makiele** [comment]
also sehr wahrscheinlich, dass der ausgegebene key müll ist?

**Comment by chester4444** [comment]
ich hab grad noch was neues eingecheckt - teste mal

**Comment by makiele** [comment]
selbes endprodukt

```
Message received in topic: /sm/encrypted

4C 47 5A 67 73 43 6E B9 4F 20 00 01 00 5E 2B 10
F9 C9 F2 E6 2A E3 D3 46 63 11 18 72 A7 37 EF 5A
76 A0 54 57 23 1A E5 2C 59 1B 0D BF 7D 24 D2 C3
B6 22 F4 DD B4 18 EA 80 27 C0 21 E1 A3 0E 0A C6
0B 80 3C AC 89 C6 13 01 5E E3 E4 E3 12 4D 89 4D
06 F7 22 4A EE 2F 8B 83
gcm_iv:
0000 - 4c 47 5a 67 73 43 6e b9-00 01 00 5e               LGZgsCn....^
gcm_ct:
0000 - 2b 10 f9 c9 f2 e6 2a e3-d3 46 63 11 18 72 a7 37   +.....*..Fc..r.7
0010 - ef 5a 76 a0 54 57 23 1a-e5 2c 59 1b 0d bf 7d 24   .Zv.TW#..,Y...}$
0020 - d2 c3 b6 22 f4 dd b4 18-ea 80 27 c0 21 e1 a3 0e   ..."......'.!...
0030 - 0a c6 0b 80 3c ac 89 c6-13 01 5e e3 e4 e3 12 4d   ....<.....^....M
0040 - 89 4d 06 f7 22 4a ee 2f-8b 83                     .M.."J./..


Ciphertext:
0000 - 2b 10 f9 c9 f2 e6 2a e3-d3 46 63 11 18 72 a7 37   +.....*..Fc..r.7
0010 - ef 5a 76 a0 54 57 23 1a-e5 2c 59 1b 0d bf 7d 24   .Zv.TW#..,Y...}$
0020 - d2 c3 b6 22 f4 dd b4 18-ea 80 27 c0 21 e1 a3 0e   ..."......'.!...
0030 - 0a c6 0b 80 3c ac 89 c6-13 01 5e e3 e4 e3 12 4d   ....<.....^....M
0040 - 89 4d 06 f7 22 4a ee 2f-8b 83                     .M.."J./..
Plaintext:
0000 - 6d 97 b0 5a ec 1a 9f 17-bc 31 31 61 f9 e4 16 8a   m..Z.....11a....
0010 - 48 cc 2b 43 0f 70 0b 4f-0d d1 c5 1c 0b 63 14 76   H.+C.p.O.....c.v
0020 - d8 0c b6 15 92 8b 66 cb-b8 77 f0 86 37 c4 5b 3f   ......f..w..7.[?
0030 - 52 55 ae a2 63 75 7b 21-2c cb 45 71 c0 9f 6b f8   RU..cu{!,.Eq..k.
0040 - 5a 56 dc 7f 19 38 59 d8-0f a2                     ZV...8Y..
```

**Comment by chester4444** [comment]
ich check mal kurz meinen Frame/Key und lösche den Auth-Tag raus

**Comment by chester4444** [comment]
Hab nun einen frame von mir genommen, obwohl ich den AUTH-Tag
dabei habe, USE_AAD auf 0 gesetzt und bekomme folgendes -

schaut so aus, als ob dein Schlüssel nicht passt, du kannst ihn mir
gerne (per PN, wenn das geht) mal zukommen lassen,  wenn er
eh nicht stimmt, kann ich eh nix damit anfangen (sonst auch nicht wirklich) 

```Message received in topic: /sm/encrypted

4C 47 5A 67 72 8A 17 DA 5E 30 00 4E BF 02 31 9F
C4 6F A8 EB BB 20 58 01 73 FA 5D E2 33 13 67 74
26 82 0B D7 0D 55 81 3B CB 66 43 01 26 65 9B 7F
64 9B 95 FD 8B E1 51 03 C5 1D 72 3D 8B 09 E6 D4
76 62 3E 3A 40 68 A1 D5 02 98 F0 D9 9B 58 AC 14
2E CA 4E 2D 2C 0F FA 1A 63 84 00 98 86 FC 0D 2C
74 05 10 80 32 27 85 BE CD
gcm_iv:
0000 - 4c 47 5a 67 72 8a 17 da-00 4e bf 02               LGZgr....N..
gcm_ct:
0000 - 31 9f c4 6f a8 eb bb 20-58 01 73 fa 5d e2 33 13   1..o... X.s.].3.
0010 - 67 74 26 82 0b d7 0d 55-81 3b cb 66 43 01 26 65   gt&....U.;.fC.&e
0020 - 9b 7f 64 9b 95 fd 8b e1-51 03 c5 1d 72 3d 8b 09   ..d.....Q...r=..
0030 - e6 d4 76 62 3e 3a 40 68-a1 d5 02 98 f0 d9 9b 58   ..vb>:@h.......X
0040 - ac 14 2e ca 4e 2d 2c 0f-fa 1a 63 84 00            ....N-,...c..


Ciphertext:
0000 - 31 9f c4 6f a8 eb bb 20-58 01 73 fa 5d e2 33 13   1..o... X.s.].3.
0010 - 67 74 26 82 0b d7 0d 55-81 3b cb 66 43 01 26 65   gt&....U.;.fC.&e
0020 - 9b 7f 64 9b 95 fd 8b e1-51 03 c5 1d 72 3d 8b 09   ..d.....Q...r=..
0030 - e6 d4 76 62 3e 3a 40 68-a1 d5 02 98 f0 d9 9b 58   ..vb>:@h.......X
0040 - ac 14 2e ca 4e 2d 2c 0f-fa 1a 63 84 00            ....N-,...c..
Plaintext:
0000 - 0f 00 53 2a 47 0c 07 e4-0c 08 02 01 02 23 ff 80   ..S*G........#..
0010 - 00 00 02 0e 12 00 e8 12-00 ea 12 00 e8 12 01 2d   ...............-
0020 - 12 00 db 12 00 af 06 00-00 03 76 06 00 00 00 00   ..........v.....
0030 - 06 00 12 34 56 06 00 00-00 00 12 00 33 12 00 3b   ............3..;
0040 - 12 00 3f 09 08 31 32 33-34 35 36 37 38            ..?..12345678
Die 08.12.2020 01:02:35 | 232 V | 234 V | 232 V |  3.01 A |  2.19 A |  1.75 A |   886 W | 12345.678 kWh|
```

**Comment by makiele** [comment]
alles klar, vielen dank für deine mühe!
wo lasse ich dir den key am besten zukommen?

**Comment by chester4444** [comment]
chester4444@wolke7.net

**Comment by chester4444** [comment]
Den CRC könnte man noch checken, um einen Übertragungsfehler auch auszuschließen.

**Comment by makiele** [comment]
wunderbar, ich werde morgen frische frames auslesen (um sicherzustellen, dass sich in der zwischenzeit nichts verändert hat) und lasse dir dann alles zukommen.

**Comment by chester4444** [comment]
CRC von dem Frame da oben ist ok - hab ich grad gecheckt

**Comment by chester4444** [comment]
Ich habe nun den decrypter so geändert, dass er vollständige HDLC frames benötigt - ich habe die README angepasst. er überprüft dann den CRC und versucht dann zu dekodieren,
USE_AAD muss auf 0 gestellt werden, wenn keine Authentifizierung dabei ist, wobei
ich das nicht testen kann - könnte sein, dass da noch was geändert werden muss.

**Comment by makiele** [comment]
habe dir mal alles zukommen lassen

**Comment by chester4444** [comment]
Habs bekommen, CRC ist ok, IV und CT ist alles am richtigen Platz,
aber es kommt nichts Vernünftiges raus (siehe unten).

Hab heute mit einem Techniker von Netz Bgld. Kontakt aufgenommen. Laut ihm hatte der kolportierte Bug in der Firmware nichts mit der Verschlüsselung zu tun - da gings um andere Dinge.
Ich geh da nicht näher drauf ein, nur so viel - für mich klang das plausibel.

Es macht bei meinen Frames keinen Unterschied, ob ich nach dem erfolgreichen Entschlüsseln optional auch noch den Auth-Tag verifiziere. Entschlüsselt wird byte-weise, d.h der Auth-Tag, der ja hinten dranhängt beeinflusst die Entschlüsselung des Ciphers nicht. Also an diesem kleinen Unterschied (0x30 vs 0x20) sollte es nicht scheitern.

Das Verfahren ist lt. GreenBook definitiv AES-128-GCM egal ob mit/ohne Authentifizierung.

```Message received in topic: /sm/encrypted

7E A0 67 CE FF 03 13 38 BD E6 E7 00 DB 08 4C 47
5A 67 73 29 0E 4F 4F 20 00 05 06 75 D9 92 2B 4E
64 59 8C 61 43 3D C6 84 77 54 46 73 5C 80 1B 63
4B 36 45 30 C8 86 3D 56 0F 7D 95 34 51 E6 2A 54
15 BD F2 44 C3 31 26 D3 A7 7C FD 3D B8 84 A1 5F
70 5E 2C 15 B4 F4 2C AC 89 D6 DB 86 B7 1D D0 36
EE 37 17 24 F8 E0 3B 54 7E
CRC ok

Ciphertext length: 74
gcm_iv:
0000 - 4c 47 5a 67 73 29 0e 4f-00 05 06 75               LGZgs).O...u
gcm_ct:
0000 - d9 92 2b 4e 64 59 8c 61-43 3d c6 84 77 54 46 73   ..+NdY.aC=..wTFs
0010 - 5c 80 1b 63 4b 36 45 30-c8 86 3d 56 0f 7d 95 34   \..cK6E0..=V.}.4
0020 - 51 e6 2a 54 15 bd f2 44-c3 31 26 d3 a7 7c fd 3d   Q.*T...D.1&..|.=
0030 - b8 84 a1 5f 70 5e 2c 15-b4 f4 2c ac 89 d6 db 86   ..._p^,...,.....
0040 - b7 1d d0 36 ee 37 17 24-f8 e0                     ...6.7.$..

Plaintext:
0000 - b5 f1 fe 14 be 54 1d 68-59 9f d5 ed aa b6 57 57   .....T.hY.....WW
0010 - 7c 4a 91 f7 58 19 7c 66-bc aa a4 d0 c4 12 db 49   |J..X.|f.......I
0020 - 7a e3 cd 01 2a 06 87 9b-75 58 11 88 ec bb 4f de   z...*...uX....O.
0030 - 45 50 e6 a8 f2 b7 ad 83-35 de dd d6 db 48 88 22   EP......5....H."
0040 - b2 26 c0 eb a2 3a 59 c9-83 f6                     .&...:Y...

(null) 159.89.7528 237:170:182 | 6524 V | 48298 V | 53444 V | 561.37 A | 583.17 A | 107.58 A | -1686808559 W | 1357293.810 kWh|```

**Comment by chester4444** [comment]
Ich habe den Schlüssel ein wenig verändert (Big/Little Endian) - aber das half nix.
Bei einem meiner anderen Projekte hatte ich mal den Schlüssel falsch interpretiert, da
hilft alles nix, wenn der nicht passt.

Anbieten kann ich: 
Ich könnte mal einen deiner Frames in meinen Arduino-basierten esp-smartmeter reinfüttern, 
der verwendet eine andere Library.

**Comment by makiele** [comment]
aber das riecht schon heftig nach fehler der wiener netze, oder? nutzer des DLMSDirector berichten eben auch, dass sich ihre wn-meter nicht entschlüsseln lassen.

ich wüsste sonst auch keinen ansatz mehr...
und mit den wiener netzen kommunizieren bzw. diskutieren wird ein spaß...

**Comment by pocki80** [comment]
Ja, sieht für mich inzwischen auch so aus, was wäre der KEY falsch, den die WienerNetze im Webportal anzeigen.
Über eine brute-force-attacke den eigenen Key zu erraten werden wir nicht erleben.

Bleibt nur eine Möglichkeit: die WienerNetze mit Supportanfragen befüttern und darauf setzen, dann viele unabhängige Kontaktaufnahmen etwas bewegen.

**Comment by chester4444** [comment]
Besser als über den Support wäre sicher, den "Seiteneingang" zu nutzen. Ich habe meinen Bekannten, der in der "Nähe" der WN arbeitet, gerade angerufen. Er schaut mal, ob er jemanden kennt, der jemanden kennt ...

**Comment by pocki80** [comment]
Ja super, ich hoffe dein "Seiteneingang" kann einen passenden Ansprechpartner finden und auf das Thema ansetzen :-)
Mein iMac (Late 2015) schafft rund 1.25 Millionen zufällig generierte Keys pro Sekunde. Kann also maximal 3,15e27 Tage dauern... Vielleicht sogar wahrscheinlich, bis vor der Rückmeldung der WN einen Glückstreffer zu landen :-)

**Comment by chester4444** [comment]
> Ja super, ich hoffe dein "Seiteneingang" kann einen passenden Ansprechpartner finden

Mein Kontakt hat die Info bekommen, man soll sich auch bei solch speziellen Fragen 
einfach an die Hotline per Telefon bzw. email wenden, die geben das dann an die
Spezialisten, bzw. "Zählerhersteller" weiter.

Viel Glück.

**Comment by pocki80** [comment]
Bedeutet: unbedingt anrufen und schreiben!
Habe ich selbst heute schon gemacht indem ich die Zufriedenheitsumfrage für meinen seit 10 Tagen unbeantworteten Supportfall ausführlich kommentiert habe.

**Comment by chester4444** [comment]
Ich hab nun auch mit meinem _**esp-smartmeter**_ kurz die Frame/key Kombination von @makiele getestet.
Einmal mit AES-GCM-128 und einmal mit AES-CTR-128 (was im Fall „ohne Auth.“ gleichwertig ist): es kommt beidemale das gleiche (unsinnige) Ergebnis raus.

Die Schlüssel kommen von L+G ja auch selbst verschlüsselt an den Netzbetreiber, eventuell ist da
was schief gegangen (falsch/gar nicht entschlüsselt ins Webportal gestellt).

Wenn die das einmal kurz testen würden, wäre das zumindest geklärt.
Zum Zählerstandauslesen verwenden die ja einen Masterkey, daher fällt ihnen das nicht auf.

**Comment by pocki80** [comment]
> Die Schlüssel kommen von L+G ja auch selbst verschlüsselt an den Netzbetreiber, eventuell ist da
> was schief gegangen (falsch/gar nicht entschlüsselt ins Webportal gestellt).

Du meinst, der dargestellte Key ist selbst chiffriert?

**Comment by chester4444** [comment]
Die Verteilung de Schlüssel erfolgt definitiv verschlüsselt

**Comment by chester4444** [comment]
So ein Problem hatte ich bei meinem Wasserzähler, war gar nicht so leicht mit dem Techniker gemeinsam an den eigentlichen Schlüssel zu kommen

**Comment by pocki80** [comment]
Denkt ihr, ich könnte anhand der S/N meines Zählers den korrekten Key vom Zählerhersteller bekommen?

**Comment by chester4444** [comment]
Also ich habe beidemale (Wasser und Strom) die Schlüssel in chiffrierter Form bekommen (per mail)
und auf einem anderen Kanal (SMS) den Schlüssel um zu dechiffrieren.

Ich habe nun auch eine freundliche Anfrage an die smartmeter-Abteilung per mail gestellt.

**Comment by chester4444** [comment]
WN haben mir auf meine Frage, ob ich den AES Schlüssel irgendwie noch aufbereiten muss, geantwortet:

> Sie müssen den Schlüssel vom Webportal eingeben. Dieser Schlüssel muss nicht konfiguriert werden. 
>Die Wiener Netze GmbH stellt nur den Schlüssel zur Verfügung, alles andere müssen Sie mit dem Hersteller des Endgerätes machen.

**Comment by pocki80** [comment]
Hm, diese Info schafft mehr Verwirrung, als sie beseitigen sollte und zeigt, dass die WN nicht so recht wissen, worüber sie hier informieren.

>Dieser Schlüssel muss nicht konfiguriert werden.
Das könnte bedeuten: Der Kunde/Strombezieher muss den Key nicht in seinem Smartmeter eingeben. No na, wie denn auch.

>mit dem Hersteller des Endgerätes machen
Das könnte bedeuten: der Hersteller jenes Geräts/Software, das die Infrarot-Daten empfängt.

Nun, beides hilft nicht wirklich, weil ersteres wussten wir ja schon.
Zweiteres haben wir auch gemacht und kann sich in unserem Fall nur auf Software beziehen. Da hat sowohl dieser "decrypter", als auch Gurux mit dem DLMSDirector schon bewiesen, dass der Key falsch ist und die Software mit den Daten von SmartMetern anderer Stromlieferanten ordnungsgemäß funktioniert.

**Comment by makiele** [comment]
> 
> 
> WN haben mir auf meine Frage, ob ich den AES Schlüssel irgendwie noch aufbereiten muss, geantwortet:
> 
> > Sie müssen den Schlüssel vom Webportal eingeben. Dieser Schlüssel muss nicht konfiguriert werden.
> > Die Wiener Netze GmbH stellt nur den Schlüssel zur Verfügung, alles andere müssen Sie mit dem Hersteller des Endgerätes machen.

selbige antwort erhalten - mir wurde aber aus dem bekanntenkreis auch mitgeteilt, dass landis+gyr keine infos an endnutzer rausgibt, weil wir laut ihrer definition nicht die kunden sind - sondern die wiener netze. eine anfrage werde ich dazu aber noch rausschicken.

**Comment by makiele** [comment]
vielleicht gibt es hoffnung

> ... I got some responses from Wiener Netze and wrote some additional messages with a new bug oft the meter firmware.
> Finally I got the message that failures were found and that the developers are working on it.
> Ok everyone can write such a messge :-) Maybe that is true or not.... I don't know but thats the first message where the say that something is not working as expected.
> 
> The will provide an update as soon as possible. Normally they need weeks for a response. We will see how much weeks they will need for bugfixing :D

Quelle: http://www.gurux.fi/node/14733?page=2

**Comment by pocki80** [comment]
WienerNetze informierte mich soeben per Mail, dass sie tatsächlich einen Fehler aufdecken konnten und der dargestellte Key offenbar falsch ist. Sie würden bereits an der Behebung des Problems arbeiten und erhoffen sich die Korrektur noch im Laufe der Woche.
Klingt mal vielversprechend - mal sehen ob in den nächsten Tagen tatsächlich ein anderer Key im Webportal auftaucht, der dann hoffentlich die HDLC-Frames entschlüsseln wird :-)

**Comment by chester4444** [comment]
Das hört sich schon mal sehr gut an.

**Comment by pocki80** [comment]
Neuer Key wird nun im WebIF angezeigt!
Entschlüsselung funktioniert damit nun bei mir.
Hurray.

**Comment by chester4444** [comment]
Freut mich, dass es nun funtkioniert.

**Comment by makiele** [comment]
kann bestätigen, der neue key funktioniert. vielen dank für die tatkräftige unterstützung @chester4444 

@pocki80 konntest du schon den plaintext vollständig interpretieren?

**Comment by chester4444** [comment]
> konntest du schon den plaintext vollständig interpretieren?

zeig mal den plaintext

**Comment by pocki80** [comment]
Schau mal hier:
https://gist.github.com/pocki80/941fa090a8d6269a9b3b68c195f8750f

**Comment by makiele** [comment]
@chester4444 plaintext sieht beim e450 wie folgt aus:
```

Plaintext:
0000 - 0f 00 05 06 78 0c 07 e4-0c 08 02 08 2e 12 ff 80   ....x...........
0010 - 00 00 02 09 09 0c 07 e4-0c 08 02 08 2e 12 ff 80   ................
0020 - 00 00 06 00 09 0f d0 06-00 00 23 e1 06 00 00 8a   ..........#.....
0030 - 5c 06 00 05 8c 7b 06 00-00 00 35 06 00 00 00 00   \....{....5.....
0040 - 06 00 00 00 00 06 00 00-00 44                     .........D

Die 08.12.2020 08:46:18 | 3079 V | 3080 V | 2094 V | 654.08 A |  0.06 A | 23.19 A | 100663331 W | 100664.716 kWh|

```

**Comment by chester4444** [comment]
Danke, alles klar, Zeitstempel ist drin (sogar an gleicher Stelle), 
jedoch bietet WienerNetze keine Daten über aktuelle Spannungen/Ströme
sondern im Gegenzug bekommt man im- und exportierte Blindleistung und Blindenergie.
Wirkleistung und Wirkenergie (in/out) ist natürlich da, nur alles an anderen Positionen (siehe @pocki80)

**Comment by makiele** [comment]
cool, vielen dank!

**Comment by pocki80** [comment]
Noch eine Frage zum Thema WienerNetze: mir fällt auf, dass die Uhrzeit laut Timestamp des HDLC-Datenpakets etwa 4-5 Sekunden nachgeht. Soll bedeuten: ich empfange um 12:00:00 ein Paket mit einem Timestamp 11:59:55, dann eine Sekunde danach das Nächste (um 12:00:01) mit einem Timestamp 11:59:56.

Kann das bedeuten, dass die WienerNetze die Uhrzeit des SmartMeters nicht sauber gegen einen NTP-Server einstellen?
